### PR TITLE
convert all loops to higher order functions

### PR DESCRIPTION
**Pull request by hardy925**
**Description**

remove iterators for higher-order functions

**Benchmarks** 🤷 
develop:
Screen Shot 2021-01-26 at 5 46 07 AM

higher_order:
Screen Shot 2021-01-26 at 5 47 02 AM

posting for comments - not sure what I am even trying.

### CODE REVIEW

**Comment by hardy925** [comment]
Probably shouldn't go in this direction. Bit o a waste of a night but good to know at least.

**Comment by ChrisDufourMB** [comment]
Definitely an interesting test. I wonder what the performance looks like after having gone through the babel -> js conversion as part of us supporting node js. Would it transpile the iterators to for loops to improve performance?

**Comment by hardy925** [comment]
closing this out, I'll bee adding a `benchmark` PR from another branch

**Comment by hardy925** [comment]
^

**Pull request closed without merging**
